# Generated by Django 2.2.11 on 2020-03-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1_app', '0002_auto_20200331_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='notes',
            new_name='quotes',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='updated_at',
        ),
    ]
