# Generated by Django 2.2.11 on 2020-03-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial1_app', '0003_auto_20200331_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='quotes',
            new_name='description',
        ),
    ]
