# Generated by Django 2.2.11 on 2020-04-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial1_app', '0004_auto_20200331_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authors', to='trial1_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
