# Generated by Django 2.2.11 on 2020-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1_app', '0005_auto_20200402_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='user_who_liked',
            field=models.ManyToManyField(related_name='blogs_liked', to='trial1_app.User'),
        ),
    ]
